version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      SECRET_KEY: "${SECRET_KEY}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWD: "${DB_PASSWD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
    command: python3 manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
