name: telegram-notify-on-pull-requests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Notify about pull request
    runs-on: ubuntu-latest
    steps:
      - name: telegram-notify-on-pull-requests
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New Pull Request from ${{ github.actor }}

            https://github.com/DAKExDUCK/duck-it/pulls